### ISSUE TITLE
Incompatible installation when using FirebaseCore

### ISSUE THREAD

**Issue by nissaba** [ABTSoftware/PodSpecs3.x#2]
I have a project that is using FirebaseCore and we evaluating if we will buy a Scicharts license. We are not able to install both SciChart and Firebase at the same time. 

If we install SciCharts by itself self no problem. 
If we install Firebase by itself self no problem. 
If we try to get both of them to install we get this error: 

```


Update all pods
Updating local specs repositories
Analyzing dependencies
[!] Unable to find a specification for `Firebase/Core`

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```

I have attached the test project I made to evaluate this. 
[podfile.zip](https://github.com/ABTSoftware/PodSpecs3.x/files/4237682/podfile.zip)

this is the GitHub for the test project https://github.com/nissaba/SciChartTest

**Comment by andriypohorilko** [comment]
Hi, there.
Thanks for a request. 
Please, try to add one more source to your podfile: 
source 'https://github.com/CocoaPods/Specs.git'

See the example below: 

> source 'https://github.com/CocoaPods/Specs.git' 
source 'https://github.com/ABTSoftware/PodSpecs3.x.git'

Be patient while cloning spec repo 'cocoapods' from 'https://github.com/CocoaPods/Specs.git'
It could take a few minutes
Let us know if it helped.

**Comment by ehmjaysee** [comment]
Same problem happened to me. Solution is to delete your derived data folder and rebuild.
